### PR TITLE
make the ASI EFW work

### PR DESCRIPTION
**Pull request by d33psky**
The session debug log shows the working functionality best : 

2016-10-12T21:34:59: ASI Wheel: Entering ASIWHEEL::Connect
2016-10-12T21:34:59: ASI Wheel: ASIWHEEL::Connect id 0
2016-10-12T21:34:59: ASI Wheel: ASIWHEEL::Connect 5 filter slots
2016-10-12T21:34:59: ASI Wheel: ASIWHEEL::Connect current filter position 1
2016-10-12T21:35:12: ASI Wheel: Setting current filter to slot 2
2016-10-12T21:35:12: ASI Wheel: Entering ASIWHEEL::SelectFilter target 2
2016-10-12T21:35:15: ASI Wheel: ASIWHEEL::SelectFilter Done moving to 2

### CODE REVIEW

**Comment by knro** [comment]
Timer was changed from 500ms to 3500ms, why?

**Comment by d33psky** [comment]
That was just determined experimental to be the time it took for a position change. It can be lowered back to 500 ms of course but it should not have much effect. I'm indifferent to the choice here; all will work.

**Comment by GinaDavis** [comment]
Where can I download the INDI driver for the ZWO EFW please?  I'm in the process of setting up a Linux system using the Raspberry Pi 3 B and have the ASI1600MM-Cool which is working with KStars/Ekos and INDI server and the EFW for which a driver is required.
Thanks.

**Comment by knro** [comment]
It's already in INDI

**Pull request merged**
